### ISSUE TITLE
Remote ComfyUI support?

### ISSUE THREAD

**Issue by ifsheldon** [AlexanderDzhoganov/ComfyTextures#1]
Hi! Awesome work!

https://github.com/AlexanderDzhoganov/ComfyTextures/blob/4a5ef6cb3a274047ec1c857840a60707a09487bd/Plugins/ComfyTextures/Source/ComfyTextures/Public/ComfyTexturesWidgetBase.h#L54

I want to use a remote ComfyUI which runs on a powerful server. Do you think that I can modify this line to support that? Or, can I just tweak some settings to do that?

Thanks!

**Comment by AlexanderDzhoganov** [comment]
Working on this.

**Comment by AlexanderDzhoganov** [comment]
https://github.com/AlexanderDzhoganov/ComfyTextures/commit/dbc20a1de7129a2e0732f6c88e5ae4efe85fa0f4 adds support for a remote instance
